sammba-mri/sammba-mri

- .travis.yml
- continuous_integration/install.sh
- continuous_integration/show-python-packages-versions.py
- sammba/version.py
- setup.py
try fix travis failure. Just added networkx and nipype to nistats install and travis configuration file
> mimic other packages travis and install files

- varianagilentFIDtoNIfTI.py
> copy paste of VarianAgilentFIDtoNIfTI.py

- sammba/externals/nipype/interfaces/afni/utils.py
- sammba/registration/func.py
- sammba/registration/struct.py
useful when brain extraction fails
> [MRG + 1] expose rbt for bias correction and fix brain_volume type in doc

- README.rst
because I copy-pasted too quickly, the package name was false ! fixing it
> [MRG +1] correct package name

- sammba/io_conversions/bruker_dicom.py
only accept EnIm*.dcm
simplifications to improve os and python version portability
> [MRG+1] dicom convert improvements

- sammba/registration/func.py
> [MRG] keep mvt parameters in outputs

- sammba/registration/struct.py
> [MRG] Unifize names

- sammba/registration/struct.py
as this stuff is already agreed on, I'll merge immediately, especially as it is blocking more important changes
> Unifize names

- sammba/externals/nipype/interfaces/afni/preprocess.py
- sammba/externals/nipype/interfaces/afni/utils.py
- sammba/registration/struct.py
> fix verbosity

- sammba/registration/struct.py
> [MRG + 1] fix qwarp not initialized

- sammba/data_fetchers/__init__.py
- sammba/data_fetchers/atlas.py
- sammba/data_fetchers/tests/test_atlas.py
added a function to extract brain and grey matter masks from dorr atlas labels, as well as eroded corpus callosum and ventricles masks which can be useful in functional connectivity etc
> [MRG] add dorr 2008 tissue masks

- sammba/registration/struct.py
> fix refit bug

- continuous_integration/install.sh
- doc/introduction.rst
- sammba/externals/nipype/interfaces/ants/__init__.py
- sammba/externals/nipype/interfaces/ants/base.py
- sammba/externals/nipype/interfaces/ants/legacy.py
- sammba/externals/nipype/interfaces/ants/registration.py
- sammba/externals/nipype/interfaces/ants/resampling.py
- sammba/externals/nipype/interfaces/ants/segmentation.py
- sammba/externals/nipype/interfaces/ants/utils.py
- sammba/externals/nipype/interfaces/ants/visualization.py
- sammba/registration/func.py
> [MRG + 1]: try install ants

- continuous_integration/install.sh
- sammba/externals/nipype/interfaces/fsl/__init__.py
- sammba/externals/nipype/interfaces/fsl/aroma.py
- sammba/externals/nipype/interfaces/fsl/base.py
- sammba/externals/nipype/interfaces/fsl/dti.py
- sammba/externals/nipype/interfaces/fsl/epi.py
- sammba/externals/nipype/interfaces/fsl/fix.py
- sammba/externals/nipype/interfaces/fsl/maths.py
- sammba/externals/nipype/interfaces/fsl/model.py
- sammba/externals/nipype/interfaces/fsl/possum.py
- sammba/externals/nipype/interfaces/fsl/preprocess.py
- sammba/externals/nipype/interfaces/fsl/utils.py
- sammba/registration/func.py
I can't see which field in the header contains this information, so I am putting back fslcpgeom at least temporary.
> [MRG] replace back registration.utils.copy_geometry by fslcpgeom

- sammba/externals/nipype/interfaces/afni/preprocess.py
- sammba/externals/nipype/interfaces/afni/utils.py
- sammba/registration/func.py
- sammba/registration/struct.py
I got the caching for the allineate, qwarp and catmatvec finally working ! very happy not to redo computations
> Fix caching

- doc/introduction.rst
> Chg_Intro180921

- examples/01_template/plot_register.py
Hi,
I add some informations in template creation example.
> [MRG + 1] improve template creation documentation

- examples/02_preprocessing/plot_fmri_coregistration.py
- sammba/registration/base_registrator.py
- sammba/registration/coregistrator.py
- sammba/registration/template_registrator.py
I may add each commit for each changes.
- I change mask_clipping_fraction to clipping_fraction in all files.
- make more explanation of plot_fmri_coregistration example
> [MRG + 1] improve plot_fmri_coregistration

- examples/01_template/plot_register.py
- examples/03_connectivity/plot_confounds.py
Hi,
I re-create the branch because when I updated the previous branch and tryed to push it to my repository, it doesn't work. It said that the update was rejected.
> Plot confounds cor

- sammba/registration/coregistrator.py
- sammba/registration/func.py
- sammba/registration/struct.py
- sammba/registration/template_registrator.py
- sammba/segmentation/brain_mask.py
> specify unit of brain volume

- sammba/io_conversions/utils.py
> [MRG] improve syntax

- sammba/segmentation/brain_mask.py
The naming and the parameter of the variable _mask_ need to be discuss
Fix #135
> [MRG] improve segmentation._get_volume code

- doc/reference.rst
- examples/03_connectivity/plot_confounds.py
> [MRG + 1] Plot confounds number cor

- sammba/registration/struct.py
> final changes in registration.anats_to_common

- sammba/segmentation/brain_mask.py
> [MRG] simplify brain mask file naming

- sammba/data_fetchers/func.py
- sammba/registration/utils.py
> [MRG] add raise error in _reset_affines function

- sammba/registration/struct.py
> [MRG] add segmentation.interfaces.Info to anats_to_template
